# Generated by Django 5.0.6 on 2024-07-06 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('invited_by', models.BigIntegerField(blank=True, default=0, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('sign_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
