# Generated by Django 5.0.6 on 2024-07-06 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('score_add', models.BigIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('inv_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUser.user')),
            ],
        ),
    ]
