# Generated by Django 5.0.6 on 2024-07-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppUser', '0003_remove_referral_score_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppUser.user')),
                ('user_level', models.IntegerField(default=1)),
                ('coins', models.BigIntegerField(blank=True, default=0, null=True)),
                ('coin_tasks', models.BigIntegerField(blank=True, default=0, null=True)),
                ('referral_coin', models.BigIntegerField(blank=True, default=0, null=True)),
                ('max_farm', models.BigIntegerField(blank=True, default=0.2, null=True)),
                ('farm_last_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
