# Generated by Django 5.0.6 on 2024-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppScore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
