# Generated by Django 5.0.6 on 2024-07-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppScore', '0002_alter_score_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='referral_coin',
            new_name='coin_referral',
        ),
    ]
