# Generated by Django 5.0.6 on 2024-07-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppScore', '0003_rename_referral_coin_score_coin_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='coin_referral',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='coin_tasks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='coins',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='max_farm',
            field=models.FloatField(blank=True, default=0.2, null=True),
        ),
    ]
